---
name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
  typecheck:
    name: Typecheck (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node }}
      - name: Check types
        run: npm run typecheck
